export const MOCK_STATS = [
  {
    label: "Tổng trang bị",
    value: "1,247",
    change: "+12",
    trend: "up",
    color: "#00D4AA",
    icon: "equipment",
  },
  {
    label: "Đang cho mượn",
    value: "89",
    change: "+5",
    trend: "up",
    color: "#F59E0B",
    icon: "borrow",
  },
  {
    label: "Đang bảo dưỡng",
    value: "23",
    change: "-3",
    trend: "down",
    color: "#EF4444",
    icon: "maintenance",
  },
  {
    label: "Trong kho",
    value: "1,135",
    change: "+10",
    trend: "up",
    color: "#3B82F6",
    icon: "unit",
  },
];

export const MOCK_LOAI_TRANG_BI = [
  {
    id: 1,
    ma: "SP-001",
    ten: "Máy bộ đàm Kenwood TK-2402",
    loai: "Thông tin liên lạc",
    donViTinh: "Cái",
  },
  {
    id: 2,
    ma: "SP-002",
    ten: "Ống nhòm quân sự 10x50",
    loai: "Quan sát",
    donViTinh: "Cái",
  },
  {
    id: 3,
    ma: "SP-003",
    ten: "Máy đo khoảng cách laser",
    loai: "Đo đạc",
    donViTinh: "Cái",
  },
  {
    id: 4,
    ma: "SP-004",
    ten: "Radio liên lạc Motorola",
    loai: "Thông tin liên lạc",
    donViTinh: "Cái",
  },
  {
    id: 5,
    ma: "SP-005",
    ten: "Kính nhìn đêm Gen 3",
    loai: "Quan sát",
    donViTinh: "Cái",
  },
  {
    id: 6,
    ma: "SP-006",
    ten: "Thiết bị định vị GPS",
    loai: "Định vị",
    donViTinh: "Cái",
  },
];

export const MOCK_TRANG_BI_THUC_TE = [
  {
    id: 1,
    spId: 1,
    ma: "TB-001-001",
    serial: "KW001",
    maQR: "QR-TB001001",
    cap: 1,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "TRONG_KHO",
    ngayNhap: "10/01/2024",
  },
  {
    id: 2,
    spId: 1,
    ma: "TB-001-002",
    serial: "KW002",
    maQR: "QR-TB001002",
    cap: 2,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "TRONG_KHO",
    ngayNhap: "10/01/2024",
  },
  {
    id: 3,
    spId: 1,
    ma: "TB-001-003",
    serial: "KW003",
    maQR: "QR-TB001003",
    cap: 1,
    kho: "Kho B",
    khoId: 2,
    donVi: "Đại đội 1",
    trangThai: "DANG_MUON",
    ngayNhap: "12/01/2024",
  },
  {
    id: 4,
    spId: 1,
    ma: "TB-001-004",
    serial: "KW004",
    maQR: "QR-TB001004",
    cap: 2,
    kho: "Kho B",
    khoId: 2,
    donVi: "Đại đội 1",
    trangThai: "TRONG_KHO",
    ngayNhap: "12/01/2024",
  },
  {
    id: 5,
    spId: 1,
    ma: "TB-001-005",
    serial: "KW005",
    maQR: "QR-TB001005",
    cap: 3,
    kho: "Kho C",
    khoId: 3,
    donVi: "Đại đội 2",
    trangThai: "BAO_DUONG",
    ngayNhap: "15/01/2024",
  },
  {
    id: 6,
    spId: 1,
    ma: "TB-001-006",
    serial: "KW006",
    maQR: "QR-TB001006",
    cap: 2,
    kho: "Kho C",
    khoId: 3,
    donVi: "Đại đội 2",
    trangThai: "TRONG_KHO",
    ngayNhap: "15/01/2024",
  },
  {
    id: 7,
    spId: 2,
    ma: "TB-002-001",
    serial: "BIN001",
    maQR: "QR-TB002001",
    cap: 1,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "TRONG_KHO",
    ngayNhap: "20/01/2024",
  },
  {
    id: 8,
    spId: 2,
    ma: "TB-002-002",
    serial: "BIN002",
    maQR: "QR-TB002002",
    cap: 2,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "TRONG_KHO",
    ngayNhap: "20/01/2024",
  },
  {
    id: 9,
    spId: 2,
    ma: "TB-002-003",
    serial: "BIN003",
    maQR: "QR-TB002003",
    cap: 1,
    kho: "Kho D",
    khoId: 4,
    donVi: "Đặc công",
    trangThai: "DANG_MUON",
    ngayNhap: "22/01/2024",
  },
  {
    id: 10,
    spId: 2,
    ma: "TB-002-004",
    serial: "BIN004",
    maQR: "QR-TB002004",
    cap: 3,
    kho: "Kho D",
    khoId: 4,
    donVi: "Đặc công",
    trangThai: "TRONG_KHO",
    ngayNhap: "22/01/2024",
  },
  {
    id: 11,
    spId: 3,
    ma: "TB-003-001",
    serial: "LRF001",
    maQR: "QR-TB003001",
    cap: 1,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "BAO_DUONG",
    ngayNhap: "05/02/2024",
  },
  {
    id: 12,
    spId: 3,
    ma: "TB-003-002",
    serial: "LRF002",
    maQR: "QR-TB003002",
    cap: 2,
    kho: "Kho C",
    khoId: 3,
    donVi: "Đại đội 2",
    trangThai: "TRONG_KHO",
    ngayNhap: "05/02/2024",
  },
  {
    id: 13,
    spId: 5,
    ma: "TB-005-001",
    serial: "NVG001",
    maQR: "QR-TB005001",
    cap: 1,
    kho: "Kho A",
    khoId: 1,
    donVi: "Ban chỉ huy",
    trangThai: "TRONG_KHO",
    ngayNhap: "18/02/2024",
  },
  {
    id: 14,
    spId: 5,
    ma: "TB-005-002",
    serial: "NVG002",
    maQR: "QR-TB005002",
    cap: 1,
    kho: "Kho D",
    khoId: 4,
    donVi: "Đặc công",
    trangThai: "DANG_MUON",
    ngayNhap: "18/02/2024",
  },
  {
    id: 15,
    spId: 6,
    ma: "TB-006-001",
    serial: "GPS001",
    maQR: "QR-TB006001",
    cap: 2,
    kho: "Kho B",
    khoId: 2,
    donVi: "Đại đội 1",
    trangThai: "DANG_MUON",
    ngayNhap: "01/03/2024",
  },
  {
    id: 16,
    spId: 6,
    ma: "TB-006-002",
    serial: "GPS002",
    maQR: "QR-TB006002",
    cap: 1,
    kho: "Kho B",
    khoId: 2,
    donVi: "Đại đội 1",
    trangThai: "TRONG_KHO",
    ngayNhap: "01/03/2024",
  },
];

export const MOCK_BORROWS = [
  {
    id: 1,
    ma: "MT-2024-001",
    nguoiMuon: "Trung úy Nguyễn Văn A",
    donVi: "Đại đội 1",
    ngayMuon: "01/06/2025",
    hanTra: "15/06/2025",
    trangThai: "DANG_MUON",
    soLuong: 3,
  },
  {
    id: 2,
    ma: "MT-2024-002",
    nguoiMuon: "Thiếu úy Trần Thị B",
    donVi: "Đại đội 2",
    ngayMuon: "28/05/2025",
    hanTra: "10/06/2025",
    trangThai: "QUA_HAN",
    soLuong: 1,
  },
  {
    id: 3,
    ma: "MT-2024-003",
    nguoiMuon: "Thượng úy Lê Văn C",
    donVi: "Ban chỉ huy",
    ngayMuon: "05/06/2025",
    hanTra: "20/06/2025",
    trangThai: "DANG_MUON",
    soLuong: 2,
  },
  {
    id: 4,
    ma: "MT-2024-004",
    nguoiMuon: "Đại úy Phạm Đức D",
    donVi: "Đại đội 3",
    ngayMuon: "03/06/2025",
    hanTra: "18/06/2025",
    trangThai: "DA_TRA",
    soLuong: 4,
  },
];

export const MOCK_MAINTENANCE = [
  {
    id: 1,
    ma: "BD-2024-001",
    tenTB: "Máy bộ đàm Kenwood",
    loaiCV: "Sửa chữa định kỳ",
    phuTrach: "Kỹ thuật viên Minh",
    ngayBD: "01/06/2025",
    trangThai: "DANG_XU_LY",
    capTruoc: 2,
    capSau: null,
  },
  {
    id: 2,
    ma: "BD-2024-002",
    tenTB: "Ống nhòm quân sự",
    loaiCV: "Vệ sinh bảo dưỡng",
    phuTrach: "Kỹ thuật viên Hùng",
    ngayBD: "03/06/2025",
    trangThai: "HOAN_THANH",
    capTruoc: 3,
    capSau: 2,
  },
  {
    id: 3,
    ma: "BD-2024-003",
    tenTB: "Kính nhìn đêm Gen 3",
    loaiCV: "Kiểm tra tổng quát",
    phuTrach: "Kỹ thuật viên Tuấn",
    ngayBD: "05/06/2025",
    trangThai: "DANG_XU_LY",
    capTruoc: 2,
    capSau: null,
  },
];

export const MOCK_UNITS = [
  { id: 1, ma: "BCH", ten: "Ban chỉ huy", capTren: null, soTB: 45 },
  { id: 2, ma: "DD1", ten: "Đại đội 1", capTren: "BCH", soTB: 120 },
  { id: 3, ma: "DD2", ten: "Đại đội 2", capTren: "BCH", soTB: 98 },
  { id: 4, ma: "DD3", ten: "Đại đội 3", capTren: "BCH", soTB: 134 },
  { id: 5, ma: "DC", ten: "Đặc công", capTren: "BCH", soTB: 67 },
];

export const MOCK_USERS = [
  {
    id: 1,
    username: "admin",
    fullName: "Thiếu tá Nguyễn Văn Hùng",
    role: "ADMIN",
    donVi: "Ban chỉ huy",
    active: true,
  },
  {
    id: 2,
    username: "ktv.minh",
    fullName: "Trung sĩ Trần Minh",
    role: "KTV",
    donVi: "Đại đội 1",
    active: true,
  },
  {
    id: 3,
    username: "user.lan",
    fullName: "Hạ sĩ Lê Thị Lan",
    role: "USER",
    donVi: "Đại đội 2",
    active: true,
  },
  {
    id: 4,
    username: "manager.duc",
    fullName: "Đại úy Phạm Đức",
    role: "MANAGER",
    donVi: "Ban chỉ huy",
    active: false,
  },
];

export const MOCK_LOGS = [
  {
    id: 1,
    user: "admin",
    action: "Thêm trang bị mới TB-2024-006",
    table: "trang_bi_thuc_te",
    ip: "192.168.1.101",
    time: "06/06/2025 08:30",
  },
  {
    id: 2,
    user: "ktv.minh",
    action: "Tạo phiếu bảo dưỡng BD-2024-003",
    table: "phieu_bao_duong",
    ip: "192.168.1.102",
    time: "06/06/2025 09:15",
  },
  {
    id: 3,
    user: "user.lan",
    action: "Tạo phiếu mượn MT-2024-004",
    table: "phieu_muon_tra",
    ip: "192.168.1.103",
    time: "05/06/2025 14:22",
  },
  {
    id: 4,
    user: "admin",
    action: "Cập nhật đơn vị DD1",
    table: "don_vi",
    ip: "192.168.1.101",
    time: "05/06/2025 10:05",
  },
  {
    id: 5,
    user: "manager.duc",
    action: "Phê duyệt phiếu bàn giao BG-2024-011",
    table: "phieu_ban_giao",
    ip: "192.168.1.104",
    time: "04/06/2025 16:40",
  },
];

export const WORK_TYPES = [
  {
    id: 1,
    ma: "SC",
    ten: "Sửa chữa định kỳ",
    moTa: "Bảo trì định kỳ theo lịch",
  },
  { id: 2, ma: "VS", ten: "Vệ sinh bảo dưỡng", moTa: "Làm sạch và bôi trơn" },
  {
    id: 3,
    ma: "KT",
    ten: "Kiểm tra tổng quát",
    moTa: "Kiểm tra toàn diện thiết bị",
  },
  {
    id: 4,
    ma: "TH",
    ten: "Thay thế linh kiện",
    moTa: "Thay thế phụ tùng hư hỏng",
  },
];

export const CATEGORIES = [
  { id: 1, ma: "TT", ten: "Thông tin liên lạc", parent: null, soSP: 234 },
  { id: 2, ma: "QS", ten: "Quan sát", parent: null, soSP: 189 },
  { id: 3, ma: "DD", ten: "Đo đạc", parent: null, soSP: 145 },
  { id: 4, ma: "DV", ten: "Định vị", parent: null, soSP: 98 },
  { id: 5, ma: "BV", ten: "Bảo vệ cá nhân", parent: null, soSP: 312 },
];

export const MOCK_KHOS = [
  {
    id: 1,
    ma: "KHO-A",
    ten: "Kho A - Ban chỉ huy",
    donVi: "Ban chỉ huy",
    viTri: "Nhà A1, tầng 1",
    tongSP: 312,
    tongMuc: 480,
  },
  {
    id: 2,
    ma: "KHO-B",
    ten: "Kho B - Đại đội 1",
    donVi: "Đại đội 1",
    viTri: "Nhà B2, tầng 2",
    tongSP: 198,
    tongMuc: 250,
  },
  {
    id: 3,
    ma: "KHO-C",
    ten: "Kho C - Đại đội 2",
    donVi: "Đại đội 2",
    viTri: "Nhà C3, tầng 1",
    tongSP: 145,
    tongMuc: 200,
  },
  {
    id: 4,
    ma: "KHO-D",
    ten: "Kho D - Dã chiến",
    donVi: "Đặc công",
    viTri: "Khu vực D, ngoài trời",
    tongSP: 67,
    tongMuc: 100,
  },
];

export const MOCK_TON_KHO = [
  {
    khoId: 1,
    kho: "Kho A",
    spId: 1,
    tenSP: "Máy bộ đàm Kenwood TK-2402",
    loai: "Thông tin liên lạc",
    cap1: 12,
    cap2: 8,
    cap3: 3,
    cap4: 1,
  },
  {
    khoId: 2,
    kho: "Kho B",
    spId: 1,
    tenSP: "Máy bộ đàm Kenwood TK-2402",
    loai: "Thông tin liên lạc",
    cap1: 5,
    cap2: 3,
    cap3: 2,
    cap4: 0,
  },
  {
    khoId: 3,
    kho: "Kho C",
    spId: 1,
    tenSP: "Máy bộ đàm Kenwood TK-2402",
    loai: "Thông tin liên lạc",
    cap1: 3,
    cap2: 1,
    cap3: 0,
    cap4: 0,
  },
  {
    khoId: 1,
    kho: "Kho A",
    spId: 2,
    tenSP: "Ống nhòm quân sự 10x50",
    loai: "Quan sát",
    cap1: 20,
    cap2: 10,
    cap3: 2,
    cap4: 0,
  },
  {
    khoId: 2,
    kho: "Kho B",
    spId: 2,
    tenSP: "Ống nhòm quân sự 10x50",
    loai: "Quan sát",
    cap1: 8,
    cap2: 4,
    cap3: 1,
    cap4: 0,
  },
  {
    khoId: 4,
    kho: "Kho D",
    spId: 2,
    tenSP: "Ống nhòm quân sự 10x50",
    loai: "Quan sát",
    cap1: 6,
    cap2: 2,
    cap3: 0,
    cap4: 0,
  },
  {
    khoId: 1,
    kho: "Kho A",
    spId: 3,
    tenSP: "Máy đo khoảng cách laser",
    loai: "Đo đạc",
    cap1: 7,
    cap2: 3,
    cap3: 1,
    cap4: 0,
  },
  {
    khoId: 3,
    kho: "Kho C",
    spId: 3,
    tenSP: "Máy đo khoảng cách laser",
    loai: "Đo đạc",
    cap1: 4,
    cap2: 2,
    cap3: 0,
    cap4: 0,
  },
  {
    khoId: 1,
    kho: "Kho A",
    spId: 5,
    tenSP: "Kính nhìn đêm Gen 3",
    loai: "Quan sát",
    cap1: 5,
    cap2: 2,
    cap3: 0,
    cap4: 0,
  },
  {
    khoId: 4,
    kho: "Kho D",
    spId: 5,
    tenSP: "Kính nhìn đêm Gen 3",
    loai: "Quan sát",
    cap1: 3,
    cap2: 1,
    cap3: 0,
    cap4: 0,
  },
];

export const MOCK_PHIEU_KHO = [
  {
    id: 1,
    ma: "PK-IN-001",
    loai: "NHAP",
    kho: "Kho A",
    nguoiLap: "admin",
    ngay: "01/06/2025",
    soLuong: 15,
    ghiChu: "Nhập kho định kỳ Q2",
  },
  {
    id: 2,
    ma: "PK-OUT-001",
    loai: "XUAT",
    kho: "Kho B",
    nguoiLap: "ktv.minh",
    ngay: "03/06/2025",
    soLuong: 8,
    ghiChu: "Xuất cho bàn giao BG-011",
  },
  {
    id: 3,
    ma: "PK-IN-002",
    loai: "NHAP",
    kho: "Kho C",
    nguoiLap: "admin",
    ngay: "04/06/2025",
    soLuong: 22,
    ghiChu: "Nhập bổ sung từ cấp trên",
  },
  {
    id: 4,
    ma: "PK-OUT-002",
    loai: "XUAT",
    kho: "Kho A",
    nguoiLap: "manager.duc",
    ngay: "05/06/2025",
    soLuong: 5,
    ghiChu: "Xuất bảo dưỡng định kỳ",
  },
  {
    id: 5,
    ma: "PK-IN-003",
    loai: "NHAP",
    kho: "Kho D",
    nguoiLap: "ktv.minh",
    ngay: "06/06/2025",
    soLuong: 10,
    ghiChu: "Nhập từ kho dã chiến",
  },
];

export const INIT_BAN_GIAO = [
  {
    id: 1,
    ma: "BG-2025-001",
    loai: "BAN_GIAO",
    khoNguon: "Kho A",
    khoDich: "Kho B",
    nguoiBanGiao: "Thiếu tá Nguyễn Văn Hùng",
    nguoiNhanGiao: "Trung úy Lê Văn C",
    donViNhan: "Đại đội 1",
    ngayLap: "01/06/2025",
    ngayThucHien: "03/06/2025",
    soLuong: 5,
    trangThai: "HOAN_THANH",
    ghiChu: "Bàn giao theo kế hoạch Q2",
    danhSachTB: [
      "TB-001-001",
      "TB-001-002",
      "TB-002-001",
      "TB-002-002",
      "TB-005-001",
    ],
  },
  {
    id: 2,
    ma: "BG-2025-002",
    loai: "CHUYEN_KHO",
    khoNguon: "Kho C",
    khoDich: "Kho D",
    nguoiBanGiao: "Đại úy Phạm Đức",
    nguoiNhanGiao: "Thiếu úy Trần Thị B",
    donViNhan: "Đặc công",
    ngayLap: "02/06/2025",
    ngayThucHien: "05/06/2025",
    soLuong: 3,
    trangThai: "DANG_XU_LY",
    ghiChu: "Điều phối dã chiến",
    danhSachTB: ["TB-001-005", "TB-001-006", "TB-003-002"],
  },
  {
    id: 3,
    ma: "BG-2025-003",
    loai: "BAN_GIAO",
    khoNguon: "Kho B",
    khoDich: "Kho A",
    nguoiBanGiao: "Trung úy Nguyễn Văn A",
    nguoiNhanGiao: "Thiếu tá Nguyễn Văn Hùng",
    donViNhan: "Ban chỉ huy",
    ngayLap: "04/06/2025",
    ngayThucHien: "",
    soLuong: 2,
    trangThai: "CHO_DUYET",
    ghiChu: "Trả lại sau bàn giao",
    danhSachTB: ["TB-001-003", "TB-006-001"],
  },
  {
    id: 4,
    ma: "BG-2025-004",
    loai: "CHUYEN_KHO",
    khoNguon: "Kho A",
    khoDich: "Kho C",
    nguoiBanGiao: "admin",
    nguoiNhanGiao: "Thượng úy Lê Văn C",
    donViNhan: "Đại đội 2",
    ngayLap: "05/06/2025",
    ngayThucHien: "",
    soLuong: 4,
    trangThai: "CHO_DUYET",
    ghiChu: "Bổ sung trang bị cho đơn vị mới",
    danhSachTB: ["TB-001-004", "TB-002-002", "TB-005-001", "TB-006-002"],
  },
];
